name: Run example UI Tests
on:
  workflow_dispatch
jobs:
  build-for-ui-test-linux-launcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: zulu
          java-version: 11
      - name: Tests
        run: |
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 1920x1080x24 &
          sleep 10
          gradle :ide-launcher:test
      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-fails-report-linux-launcher
          path: |
            ide-launcher/build/reports
